config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/show'

  devise_for :users
  root to: "pages#home"
  get 'my-profile', to: 'pages#my_profile'

  resources :flats, only: ['index', 'show'] do
    resources :bookings, only: ['create']
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :flats
  has_many :bookings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    @booking.flat = @flat
    @booking.user = current_user

    if @booking.save
      redirect_to my_profile_path
    else
      render 'flats/show', status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: ['show', 'reate']
    # if params[:query].present?
    #   @movies = @movies.where("title ILIKE ?", "%#{params[:query]}%")
    # end
  def index
    @flats = Flat.all

    if params[:query].present?
      @flats = Flat.where("name ILIKE ?", "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "flats/list", locals: { flats: @flats}, formats: [:html] }
    end
  end

  def show
    @booking = Booking.new
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user

    if @message.save
        ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/show.html.erb
<div class="container chatroom"
     data-controller="chatroom-subscription"
     data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
>
  <h1>#<%= @chatroom.name %></h1>

  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <%= render 'messages/message', message: message %>
    <% end %>
  </div>

  <%= simple_form_for [@chatroom, @message], html: {class: "d-flex"} do |f| %>
    <%= f.input :content,
      label: false,
      placeholder: "Message ##{@chatroom.name}",
      wrapper_html: {class: "flex-grow-1"}
    %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %>
  <% end %>

</div>

app/views/flats/_flat.html.erb
<div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2><%= flat.name %></h2>
      <p><%= flat.address %></p>
      <p>Bedrooms: <%= flat.bedrooms %></p>
    </div>
    <h2 class="card-trip-pricing">Owner: <%= flat.user.email %></h2>
    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
  </div>
</div>

app/views/flats/_list.html.erb
    <% flats.each do |flat| %>
      <%= link_to flat_path(flat) do %>
        <%= render 'flat', flat: flat %>
      <% end %>
    <% end %>

app/views/flats/index.html.erb
<div class="container">
<h1>Flats</h1>

  <div data-controller="search-flats">

    <%= form_with url: flats_path, method: :get, html: {class: "d-flex mb-4",
                                  data: {search_flats_target: "form"}} do |f| %>
      <%= f.text_field :query,
                        class: "form-control",
                        placeholder: "Search for a Flat",
                        value: params[:query],
                        data: {
                          search_flats_target: "input",
                          action: "keyup->search-flats#update"
                          } %>
      <%#= f.submit "Search", class: "btn btn-primary" %>
    <% end %>

    <div class="cards" data-search-flats-target="list">
      <%= render 'flats/list', flats: @flats %>
    </div>

  </div>
</div>

app/views/flats/show.html.erb
<div class="container w-50">
  <h1><%= @flat.name %></h1>
  <%= render 'flat', flat: @flat %>
  <hr>

  <%=  simple_form_for [@flat, @booking] do |f| %>
    <%= f.input :start_date, as: :date, html5: true %>
    <%= f.input :end_date, as: :date, html5: true %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="page-container">
      <%= render "shared/navbar" %>
      <main id="main-content">
        <%= yield %>
      </main>
      <%= render 'shared/footer' %>
      <%# <%= render "shared/flashes" %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.nickname %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <%= link_to "Find a Flat", flats_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/pages/my_profile.html.erb
<div class="container"  data-controller="tabs">
  <h1>My Profile page</h1>

  <ul class="tabs">
    <li data-action="click->tabs#displayFlats" data-tabs-target="flatsLink" class="active">My Flats</li>
    <li data-action="click->tabs#displayBookings" data-tabs-target="bookingsLink">My Bookings</li>
    <li data-action="click->tabs#displayRequested" data-tabs-target="requestedLink">Requested</li>
  </ul>

  <div>

    <div data-tabs-target="flats">
    <h4>My Flats</h4>
      <ul>
        <% current_user.flats.each do |flat| %>
          <li>
            <p><%= flat.name %></p>
            <p><%= flat.address %></p>
          </li>
          <hr>
        <% end %>
      </ul>
    </div>

    <div data-tabs-target="bookings" >
    <h4>My Bookings</h4>
      <ul>
        <% current_user.bookings.each do |booking| %>
          <li>
            <p><%= booking.flat.name %></p>
            <p>From: <%= booking.start_date %></p>
            <p>TO: <%= booking.end_date %></p>
          </li>
          <hr>
        <% end %>
      </ul>
    </div>

    <div data-tabs-target="requested">
    <h4>Requested</h4>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quam! Accusantium, exercitationem optio provident ducimus quasi repudiandae repellat reiciendis consectetur asperiores libero nesciunt nemo expedita rem ullam eos facilis sunt!</p>
    </div>


  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Flats", flats_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Hi, #{current_user.email}", my_profile_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>